services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
      # - "4173:4173" #for builds
    environment:
      - VITE_REACT_APP_BACKEND_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - backend

  test:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - backend
    networks:
      - app-network
    command: [ "pytest", "tests/integration_test.py", "-v" ]
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app # Adjust this path as per the container's filesystem

networks:
  app-network:
