services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - pexels_service

  pexels_service:
    build:
      context: ./pexels_service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./pexels_service/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
      # - "4173:4173" #for builds
    environment:
      - VITE_REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: [ "pytest", "tests/integration_test.py", "-v" ]
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
