from typing import List
from app.models import Ingredient, DrinkRecipe, DrinkType, Unit

# --- In-Memory Store ---
drink_db: List[DrinkRecipe] = [
    DrinkRecipe(
        name="Mojito",
        ingredients=[
            Ingredient(name="White Rum", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Mint Leaves", amount=10, unit=Unit.PIECE),
            Ingredient(name="Lime", amount=0.5, unit=Unit.PIECE),
            Ingredient(name="Sugar", amount=2, unit=Unit.TEASPOON),
            Ingredient(name="Club Soda", amount=1, unit=Unit.TOP_UP),
        ],
        instructions=[
            "Muddle mint leaves and sugar in a glass.",
            "Add lime juice and rum.",
            "Fill the glass with ice and top it up with club soda.",
            "Stir gently and garnish with a mint sprig.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=1187766,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Martini",
        ingredients=[
            Ingredient(name="Gin", amount=60, unit=Unit.MILLILITER),
            Ingredient(name="Dry Vermouth", amount=10, unit=Unit.MILLILITER),
            Ingredient(name="Olive", amount=1, unit=Unit.PIECE),
        ],
        instructions=[
            "Pour gin and dry vermouth into a mixing glass.",
            "Fill with ice and stir for 20-30 seconds.",
            "Strain into a chilled martini glass and garnish with an olive.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=2531186,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Gin and Tonic",
        ingredients=[
            Ingredient(name="Gin", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Tonic Water", amount=1, unit=Unit.TOP_UP),
            Ingredient(name="Lime", amount=0.25, unit=Unit.PIECE),
        ],
        instructions=[
            "Pour gin into a glass filled with ice.",
            "Top it up with tonic water.",
            "Garnish with a lime wedge.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=616836,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Old Fashioned",
        ingredients=[
            Ingredient(name="Bourbon", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Sugar", amount=1, unit=Unit.TEASPOON),
            Ingredient(name="Angostura Bitters", amount=2, unit=Unit.DASH),
            Ingredient(name="Orange Peel", amount=1, unit=Unit.PIECE),
        ],
        instructions=[
            "Muddle the sugar and bitters in a glass.",
            "Add bourbon and stir with ice.",
            "Garnish with an orange peel.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=32711953,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Piña Colada",
        ingredients=[
            Ingredient(name="White Rum", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Coconut Cream", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Pineapple Juice", amount=90, unit=Unit.MILLILITER),
            Ingredient(name="Pineapple Slice", amount=1, unit=Unit.PIECE),
        ],
        instructions=[
            "Blend all ingredients with ice.",
            "Pour into a glass and garnish with a pineapple slice.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=8944950,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Margarita",
        ingredients=[
            Ingredient(name="Tequila", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Lime Juice", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Triple Sec", amount=20, unit=Unit.MILLILITER),
            Ingredient(name="Salt", amount=1, unit=Unit.TOP_UP),
        ],
        instructions=[
            "Rub a lime wedge around the rim of a glass and dip it in salt.",
            "Shake tequila, lime juice, and triple sec with ice.",
            "Strain into the prepared glass.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=1590154,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Cosmopolitan",
        ingredients=[
            Ingredient(name="Vodka", amount=45, unit=Unit.MILLILITER),
            Ingredient(name="Triple Sec", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Lime Juice", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Cranberry Juice", amount=30, unit=Unit.MILLILITER),
        ],
        instructions=[
            "Shake all ingredients with ice.",
            "Strain into a chilled martini glass.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=2336667,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Bloody Mary",
        ingredients=[
            Ingredient(name="Vodka", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Tomato Juice", amount=100, unit=Unit.MILLILITER),
            Ingredient(name="Lemon Juice", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Tabasco Sauce", amount=2, unit=Unit.DASH),
            Ingredient(name="Worcestershire Sauce", amount=2, unit=Unit.DASH),
        ],
        instructions=[
            "Shake all ingredients with ice.",
            "Strain into a tall glass and garnish with a celery stick.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=7376796,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Mai Tai",
        ingredients=[
            Ingredient(name="Rum", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Orange Curaçao", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Orgeat Syrup", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Lime Juice", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Mint Leaves", amount=2, unit=Unit.PIECE),
        ],
        instructions=[
            "Shake all ingredients with ice.",
            "Strain into a glass filled with crushed ice and garnish with mint leaves.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=12580185,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Whiskey Sour",
        ingredients=[
            Ingredient(name="Whiskey", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Lemon Juice", amount=25, unit=Unit.MILLILITER),
            Ingredient(name="Simple Syrup", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Egg White", amount=1, unit=Unit.PIECE),
        ],
        instructions=[
            "Shake all ingredients without ice to emulsify.",
            "Add ice and shake again.",
            "Strain into a glass and garnish with a cherry.",
        ],
        alcoholContent=True,
        type=DrinkType.COCKTAIL,
        imageId=28834354,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Virgin Pina Colada",
        ingredients=[
            Ingredient(name="Pineapple Juice", amount=120, unit=Unit.MILLILITER),
            Ingredient(name="Coconut Milk", amount=60, unit=Unit.MILLILITER),
            Ingredient(name="Ice Cubes", amount=5, unit=Unit.PIECE),
        ],
        instructions=[
            "Combine pineapple juice and coconut milk in a blender.",
            "Add ice cubes and blend until smooth.",
            "Pour into a chilled glass and garnish with a pineapple slice.",
        ],
        alcoholContent=False,
        type=DrinkType.MOCKTAIL,
        imageId=28575243,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Cucumber Mint Cooler",
        ingredients=[
            Ingredient(name="Cucumber", amount=4, unit=Unit.PIECE),
            Ingredient(name="Mint Leaves", amount=10, unit=Unit.PIECE),
            Ingredient(name="Lime Juice", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Sugar Syrup", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Soda Water", amount=1, unit=Unit.TOP_UP),
        ],
        instructions=[
            "Muddle cucumber and mint leaves in a shaker.",
            "Add lime juice and sugar syrup, shake well with ice.",
            "Strain into a glass and top up with soda water.",
        ],
        alcoholContent=False,
        type=DrinkType.MOCKTAIL,
        imageId=5335918,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Strawberry Basil Smash",
        ingredients=[
            Ingredient(name="Strawberries", amount=5, unit=Unit.PIECE),
            Ingredient(name="Basil Leaves", amount=4, unit=Unit.PIECE),
            Ingredient(name="Lemon Juice", amount=20, unit=Unit.MILLILITER),
            Ingredient(name="Honey", amount=1, unit=Unit.TABLESPOON),
            Ingredient(name="Soda Water", amount=1, unit=Unit.TOP_UP),
        ],
        instructions=[
            "Muddle strawberries and basil leaves in a shaker.",
            "Add lemon juice and honey, shake with ice.",
            "Strain into a glass and top up with soda water.",
        ],
        alcoholContent=False,
        type=DrinkType.MOCKTAIL,
        imageId=19297798,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Citrus Fizz",
        ingredients=[
            Ingredient(name="Orange Juice", amount=100, unit=Unit.MILLILITER),
            Ingredient(name="Lemon Juice", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Sugar Syrup", amount=15, unit=Unit.MILLILITER),
            Ingredient(name="Sparkling Water", amount=1, unit=Unit.TOP_UP),
        ],
        instructions=[
            "Mix orange juice, lemon juice, and sugar syrup in a shaker with ice.",
            "Shake well and strain into a glass.",
            "Top up with sparkling water and stir gently.",
        ],
        alcoholContent=False,
        type=DrinkType.MOCKTAIL,
        imageId=32677319,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Tropical Sunrise",
        ingredients=[
            Ingredient(name="Mango Juice", amount=80, unit=Unit.MILLILITER),
            Ingredient(name="Pineapple Juice", amount=80, unit=Unit.MILLILITER),
            Ingredient(name="Grenadine", amount=10, unit=Unit.MILLILITER),
            Ingredient(name="Ice Cubes", amount=4, unit=Unit.PIECE),
        ],
        instructions=[
            "Fill a glass with ice cubes.",
            "Pour mango and pineapple juice over the ice.",
            "Slowly drizzle grenadine to create a sunrise effect.",
        ],
        alcoholContent=False,
        type=DrinkType.MOCKTAIL,
        imageId=8679426,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Lemon Ginger Shot",
        ingredients=[
            Ingredient(name="Lemon Juice", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Ginger Juice", amount=10, unit=Unit.MILLILITER),
            Ingredient(name="Honey", amount=1, unit=Unit.TEASPOON),
        ],
        instructions=[
            "Combine all ingredients in a small glass.",
            "Stir well and serve immediately.",
        ],
        alcoholContent=False,
        type=DrinkType.SHOT,
        imageId=4443465,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Banana Oat Smoothie",
        ingredients=[
            Ingredient(name="Banana", amount=1, unit=Unit.PIECE),
            Ingredient(name="Oats", amount=3, unit=Unit.TABLESPOON),
            Ingredient(name="Milk", amount=200, unit=Unit.MILLILITER),
            Ingredient(name="Honey", amount=1, unit=Unit.TABLESPOON),
        ],
        instructions=[
            "Add all ingredients to a blender.",
            "Blend until smooth and creamy.",
            "Serve chilled.",
        ],
        alcoholContent=False,
        type=DrinkType.SMOOTHIE,
        imageId=4311550,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Berry Blast Smoothie",
        ingredients=[
            Ingredient(name="Mixed Berries", amount=100, unit=Unit.GRAM),
            Ingredient(name="Yogurt", amount=150, unit=Unit.MILLILITER),
            Ingredient(name="Honey", amount=1, unit=Unit.TABLESPOON),
        ],
        instructions=[
            "Blend berries, yogurt, and honey until smooth.",
            "Pour into a glass and serve chilled.",
        ],
        alcoholContent=False,
        type=DrinkType.SMOOTHIE,
        imageId=434295,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Green Power Smoothie",
        ingredients=[
            Ingredient(name="Spinach", amount=10, unit=Unit.PIECE),
            Ingredient(name="Banana", amount=1, unit=Unit.PIECE),
            Ingredient(name="Apple Juice", amount=150, unit=Unit.MILLILITER),
            Ingredient(name="Chia Seeds", amount=1, unit=Unit.TABLESPOON),
        ],
        instructions=[
            "Combine all ingredients in a blender.",
            "Blend until smooth and serve immediately.",
        ],
        alcoholContent=False,
        type=DrinkType.SMOOTHIE,
        imageId=5644869,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Classic Vanilla Milkshake",
        ingredients=[
            Ingredient(name="Vanilla Ice Cream", amount=3, unit=Unit.PIECE),
            Ingredient(name="Milk", amount=200, unit=Unit.MILLILITER),
            Ingredient(name="Vanilla Extract", amount=0.5, unit=Unit.TEASPOON),
        ],
        instructions=[
            "Add all ingredients to a blender.",
            "Blend until smooth.",
            "Serve in a chilled glass with whipped cream (optional).",
        ],
        alcoholContent=False,
        type=DrinkType.MILKSHAKE,
        imageId=20205949,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Chocolate Banana Milkshake",
        ingredients=[
            Ingredient(name="Banana", amount=1, unit=Unit.PIECE),
            Ingredient(name="Chocolate Syrup", amount=2, unit=Unit.TABLESPOON),
            Ingredient(name="Milk", amount=200, unit=Unit.MILLILITER),
            Ingredient(name="Ice Cream", amount=2, unit=Unit.PIECE),
        ],
        instructions=[
            "Blend all ingredients until smooth.",
            "Pour into a tall glass and drizzle extra chocolate syrup on top.",
        ],
        alcoholContent=False,
        type=DrinkType.MILKSHAKE,
        imageId=20205951,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Fruit Party Punch",
        ingredients=[
            Ingredient(name="Orange Juice", amount=300, unit=Unit.MILLILITER),
            Ingredient(name="Pineapple Juice", amount=200, unit=Unit.MILLILITER),
            Ingredient(name="Lemon-Lime Soda", amount=1, unit=Unit.TOP_UP),
            Ingredient(name="Mixed Fruits", amount=100, unit=Unit.GRAM),
        ],
        instructions=[
            "Combine juices in a large bowl.",
            "Add soda and gently stir.",
            "Add chopped fruits and ice before serving.",
        ],
        alcoholContent=False,
        type=DrinkType.PUNCH,
        imageId=32659127,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Iced Coffee",
        ingredients=[
            Ingredient(name="Brewed Coffee", amount=150, unit=Unit.MILLILITER),
            Ingredient(name="Milk", amount=50, unit=Unit.MILLILITER),
            Ingredient(name="Ice Cubes", amount=4, unit=Unit.PIECE),
        ],
        instructions=[
            "Fill a glass with ice cubes.",
            "Pour in cold coffee and milk.",
            "Stir and serve chilled.",
        ],
        alcoholContent=False,
        type=DrinkType.COFFEE_DRINK,
        imageId=4790062,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Caramel Latte",
        ingredients=[
            Ingredient(name="Espresso", amount=30, unit=Unit.MILLILITER),
            Ingredient(name="Steamed Milk", amount=200, unit=Unit.MILLILITER),
            Ingredient(name="Caramel Syrup", amount=1, unit=Unit.TABLESPOON),
        ],
        instructions=[
            "Pour espresso into a cup.",
            "Add caramel syrup and steamed milk.",
            "Top with milk foam and a drizzle of caramel.",
        ],
        alcoholContent=False,
        type=DrinkType.COFFEE_DRINK,
        imageId=22702617,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Iced Green Tea with Lemon",
        ingredients=[
            Ingredient(name="Brewed Green Tea", amount=200, unit=Unit.MILLILITER),
            Ingredient(name="Lemon Juice", amount=20, unit=Unit.MILLILITER),
            Ingredient(name="Honey", amount=1, unit=Unit.TABLESPOON),
            Ingredient(name="Ice Cubes", amount=5, unit=Unit.PIECE),
        ],
        instructions=[
            "Mix green tea, lemon juice, and honey.",
            "Pour over a glass filled with ice.",
            "Garnish with a lemon slice.",
        ],
        alcoholContent=False,
        type=DrinkType.TEA_DRINK,
        imageId=15894951,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Masala Chai",
        ingredients=[
            Ingredient(name="Black Tea", amount=1, unit=Unit.TEASPOON),
            Ingredient(name="Milk", amount=150, unit=Unit.MILLILITER),
            Ingredient(name="Water", amount=100, unit=Unit.MILLILITER),
            Ingredient(
                name="Spice Mix (ginger, cardamom, cloves)",
                amount=1,
                unit=Unit.TEASPOON,
            ),
            Ingredient(name="Sugar", amount=1, unit=Unit.TEASPOON),
        ],
        instructions=[
            "Boil water with spices and sugar.",
            "Add tea leaves and simmer.",
            "Pour in milk, boil again, strain and serve hot.",
        ],
        alcoholContent=False,
        type=DrinkType.TEA_DRINK,
        imageId=5946612,
        isFavorite=False,
    ),
    DrinkRecipe(
        name="Classic Hot Chocolate",
        ingredients=[
            Ingredient(name="Milk", amount=250, unit=Unit.MILLILITER),
            Ingredient(name="Cocoa Powder", amount=2, unit=Unit.TABLESPOON),
            Ingredient(name="Sugar", amount=1, unit=Unit.TABLESPOON),
            Ingredient(name="Dark Chocolate", amount=20, unit=Unit.GRAM),
        ],
        instructions=[
            "Heat milk in a saucepan.",
            "Whisk in cocoa powder and sugar until dissolved.",
            "Add dark chocolate and stir until melted.",
            "Serve hot with whipped cream if desired.",
        ],
        alcoholContent=False,
        type=DrinkType.HOT_CHOCOLATE,
        imageId=6113408,
        isFavorite=False,
    ),
]
